Vagrant.configure("2") do |config|
 
  config.vm.box = "generic/ubuntu1804"
 
  config.vm.provider :libvirt do |domain|
           domain.memory = 1024
           domain.cpus = 2
  end
 
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      mkdir -p /root/.ssh
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
	apt-get update
	apt-get install -y mariadb-server mariadb-client
SHELL
  end

   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "galera.yml"
    ansible.sudo = true
  end
 
  config.vm.define :mariadb1 do |machine|
          machine.vm.network :private_network,
                  :ip => '192.168.123.10'
  end
  
  config.vm.define :mariadb2 do |machine|
          machine.vm.network :private_network,
                  :ip => '192.168.123.11'
  end
 

end
